devices: Include `sys/sysmacros.h` for `major()` and `minor()`
Building the source on Debian sid/unstable with libc6 2.31-5 and UUID support
(default) results in the build failure below.

      CC       tiny_initramfs-devices.o
      CC       tiny_initramfs-util.o
    devices.c: In function 'scan_devices':
    devices.c:290:15: warning: implicit declaration of function 'major' [-Wimplicit-function-declaration]
      290 |           if (major(st.st_rdev) == maj && minor(st.st_rdev) == min) {
          |               ^~~~~
    devices.c:290:33: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
      290 |           if (major(st.st_rdev) == maj && minor(st.st_rdev) == min) {
          |                                 ^~
    devices.c:290:43: warning: implicit declaration of function 'minor' [-Wimplicit-function-declaration]
      290 |           if (major(st.st_rdev) == maj && minor(st.st_rdev) == min) {
          |                                           ^~~~~
    devices.c:290:61: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
      290 |           if (major(st.st_rdev) == maj && minor(st.st_rdev) == min) {
          |                                                             ^~
      CCLD     tiny_initramfs
    /usr/bin/ld: tiny_initramfs-devices.o: in function `scan_devices':
    devices.c:(.text+0x520): undefined reference to `major'
    /usr/bin/ld: devices.c:(.text+0x539): undefined reference to `minor'
    collect2: error: ld returned 1 exit status
    make[1]: *** [Makefile:398: tiny_initramfs] Error 1

Explicitly include the header `sys/sysmacros.h`, where `major()` and `minor()`
are defined.

Resolves: https://github.com/chris-se/tiny-initramfs/issues/4